Julia 1.0:
  image: julia:1.0
  script: julia --project='@.' -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
  coverage: /Test Coverage (\d+\.\d+%)/
  after_script:
    - julia -e 'using Printf; using Pkg; Pkg.add("Coverage"); using Coverage; c, t = get_summary(process_folder()); @printf "Test Coverage %.2f%%\n" 100c/t'
